### PR TITLE
Adding ArgumentList property to Carbon_Service DSC resource

### PR DESCRIPTION
**Pull request by splatteredbits**

### CODE REVIEW

**Comment by splatteredbits** [comment]
@gigi81 I had to rollback the change you made in `Join-ServiceArgumentList.ps1`. It was causing a bunch of tests to fail. It looks like it wasn't escaping things correctly.

**Comment by gigi81** [comment]
Hi, @splatteredbits sorry I tried to test it on my machine as much as I could but I was not able to run the tests. Also the appveyor build was not working. Seems like you fixed the build now, so I will have a look into the failed tests and let you know. thanks

**Comment by splatteredbits** [comment]
@gigi81 I fixed the broken tests by reverting the extra quote handling you introduced in `Join-ServiceArgumentList.ps1`. Let me know if there's an edge case or something else that `Install-Service` doesn't handle. Also, I released your change this weekend in version 2.6.0.

**Comment by gigi81** [comment]
Hi @splatteredbits, the edge case is when you have at least a space AND double quote in one of the arguments. To pass it properly you need to surrund the argument between double quotes. Anyway, you also need to escape the double quote in the string, so you need a double double quote. So for example checking the unittest, this is incorrect:

`
$svc = Install-Service -Name $serviceName -Path $servicePath -ArgumentList "-k","Fu bar","-w",'"Surrounded By Quotes"' @installServiceParams
$svc | Should BeNullOrEmpty
$Global:Error.Count | Should Be 0
$svcConfig = Get-ServiceConfiguration -Name $serviceName
$svcConfig.Path | Should Be ('"{0}" -k "Fu bar" -w "Surrounded By Quotes"' -f $servicePath)
`

What I would expect is this:

`
$svcConfig.Path | Should Be ('"{0}" -k "Fu bar" -w """Surrounded By Quotes"""' -f $servicePath)
`

To make it simpler, let's say I have an argument like this: 'space and"quote'.
For the application to receive it as a single argument, you will need to pass it as '"space and""quote"' (single quotes here are just used for readability)

I hope the problem is more clear now.

**Pull request merged**
